version: '3.5'

services:
  lunch:
    build: .
    container_name: lunch
    restart: always
    environment:
      - DB_HOST=${DB_HOST:-lunchdb}
      - DB_USER=${DB_USER:-lunch}
      - DB_PW=${DB_PW:-lunch}
      - DB_NAME=${DB_NAME:-lunch}
    depends_on:
      - db
    networks:
      - db
    ports:
      - 5000:5000

  db:
    container_name: lunchdb
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-lunch}
      - POSTGRES_PASSWORD=${DB_PW:-lunch}      
      - POSTGRES_DB=${DB_NAME:-lunch}
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data/:/data/db

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge