# Builds site locally and rsyncs to server
- name: Specify git dir
  set_fact:
    git_dir: "/srv/lunch"
    server_url: "http://lunch.dvalin.tf.fi"

- name: Install npm packages
  npm:
    path: "{{ git_dir }}/lunch"
    state: present

- name: Template files containing server url
  template:
    src: src_components_Login.vue.j2
    dest: "{{ git_dir }}/lunch/src/components/Login.vue"

- name: Template files containing server url
  template:
    src: src_RequestService.js.j2
    dest: "{{ git_dir }}/lunch/src/RequestService.js"

- name: Run npm run build
  command:
    argv:
      - npm
      - run
      - build
    chdir: "{{ git_dir }}/lunch"

- name: Copy build dist
  copy:
    remote_src: yes
    mode: preserve
    src: "{{ git_dir }}/lunch/dist/"
    dest: /srv/lunch-frontend/
